modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Crimix/wrap-radial/issues"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]]
modId="warpradial"
version="${file.jarVersion}"
displayName="Wrap Radial"
updateJSONURL="https://raw.githubusercontent.com/Crimix/warp-radial/1.17/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/warp-radial"
logoFile="warp-radial-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''Commands are fine, but have you seen this radial menu, it rocks'''

[[dependencies.warpradial]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.59,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.warpradial]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.warpradial]]
    modId="blackdogsmoddinglibrary"
    mandatory=true
    versionRange="[1.1.5,)"
    ordering="BEFORE"
    side="BOTH"
