modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Crimix/wrap-radial/issues"

[[mods]]
modId="warpradial"
version="${file.jarVersion}"
displayName="Wrap Radial"
updateJSONURL="https://raw.githubusercontent.com/Crimix/warp-radial/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/warp-radial"
logoFile="warp-radial-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''Commands are fine, but have you seen this radial menu, it rocks'''

[[dependencies.warpradial]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.warpradial]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.warpradial]]
    modId="blackdogsmoddinglibrary"
    mandatory=true
    versionRange="[1.0.10,)"
    ordering="BEFORE"
    side="BOTH"
