modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Crimix/wrap-radial/issues"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]]
modId="warpradial"
version="${version}"
displayName="Wrap Radial"
updateJSONURL="${update_url}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/warp-radial"
logoFile="warp-radial-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''Commands are fine, but have you seen this radial menu, it rocks'''

[[dependencies.warpradial]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.warpradial]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.warpradial]]
    modId="blackdogsmoddinglibrary"
    mandatory=true
    versionRange="${bml_version_range}"
    ordering="BEFORE"
    side="BOTH"
